
language: python
cache: pip
python:
  - "2.7"
  - "3.6"
  - "3.5"
  - "3.4"
  - "pypy"
sudo: false # Use container-based infrastructure

install:
  - "pip install embarc_cli"
  - "pip install coverage"

script: 
  - "embarc osp --clone"
  - "cd embarc_cli"
  - "python maintest.py"
