
language: python
cache: pip
python:
  - "2.7"
  - "3.6"
  - "3.5"
  - "3.4"
  - "pypy"
#sudo: false # Use container-based infrastructure
sudo: required
dist: trusty
install:
  - "sudo apt-get update"
  - "sudo apt-get install lib32z1"
  - "sudo apt-get install dos2unix"
  - "pip install embarc_cli"
  - "pip install coverage"
  - "pip install pycodestyle"
  - "pip install pyflakes"
  
before_script:
  - "embarc toolchain --toolchain gnu --install"
  - "export PATH=$PATH:/home/travis/build/wangnuannuan/PythonLearn/embarc_cli/2018.09/bin"

script: 
  - "embarc osp --clone"
  - "cd embarc_cli"
  - "python maintest.py"
