
language: python
cache: pip
python:
  - "2.7"
  - "3.6"
  - "3.5"
  - "3.4"
  - "pypy"
#sudo: false # Use container-based infrastructure
sudo: required
dist: trusty
install:
  - "sudo apt-get update"
  - "sudo apt-get install lib32z1"
  - "sudo apt-get install dos2unix"
  - "pip install embarc_cli"
  - "pip install coverage"
  - "pip install pycodestyle"
  - "pip install pyflakes"
  
before_script:
  - bash .ci/script.sh

script: 
  - "embarc config osp --add new_osp https://github.com/foss-for-synopsys-dwc-arc-processors/embarc_osp"
  - "cd embarc_cli"
  - "python maintest.py"
