
language: python
cache:
  pip: true
  directories:
    - .cache/result
    - .cache/toolchain
python:
  - "2.7"
  - "3.6"
  - "3.5"
  - "3.4"
  - "pypy"
#sudo: false # Use container-based infrastructure
sudo: required
dist: trusty
install:
  - "sudo apt-get update"
  - "sudo apt-get install lib32z1"
  - "sudo apt-get install dos2unix"
  - "pip install embarc_cli"
  - "pip install coverage"
  - "pip install pycodestyle"
  - "pip install pyflakes"
  
before_script:
  - pip install --user awscli
  - mkdir -p .cache/toolchain
  - bash .ci/script.sh
  - aws s3 sync s3://travis-build-stages-shared-storage-test/.cache/toolchain .cache/toolchain

script: 
  - "cd embarc_cli"
  - "python maintest.py"

addons:
  artifacts:
    paths:
    - .cache/result

jobs:
  include:
    - stage: deploy
      script: 
        - "cd embarc_cli"
        - "python maintest.py"
      after_success:
              - aws s3 rm --recursive s3://travis-build-stages-shared-storage-test/.cache/toolchain # clean up after ourselves