
language: python
cache: pip
python:
  - "2.7"
  - "3.6"
  - "3.5"
  - "3.4"
  - "pypy"
sudo: false # Use container-based infrastructure

install:
  - "pip install embarc_cli"
  - "pip install unittest2"
  - "pip install html-testRunner"
  - "pip install coverage"

script: 
  - "cd rembarc_cli/test"
  - "python main.py" #"python -m unittest discover -p test_*.py"
