
language: python
cache: pip
python:
  - "2.7"
  - "3.6"
  - "3.5"
  - "3.4"
  - "pypy"
#sudo: false # Use container-based infrastructure
sudo: required
dist: trusty
install:
  - "sudo apt-get update"
  - "sudo apt-get install lib32z1"
  - "sudo apt-get install dos2unix"
  - "pip install embarc_cli"
  - "pip install coverage"
  - "embarc toolchain --toolchain gnu --version 2018.09 --install"

script: 
  - "embarc osp --clone"
  - "cd embarc_cli"
  - "python maintest.py"
